[div=bj-cards]
[div=bj-card]
[div=bj-card-title]Привет[/div]
Здесь мой список, любимое и немного статистики. Если хочешь посоветовать тайтл — пиши в личку.
[/div]
[div=bj-card]
[div=bj-card-title]Топ-3[/div]
[div=bj-top][animes ids=185,1575,431 columns=3][/div]
[/div]
[div=bj-card]
[div=bj-card-title]Ссылки[/div]
[div=bj-links][url=https://bonjourchik.ru]bonjourchik.ru[/url][url=https://shikimori.io/Bonjourchik/list/anime]Список аниме[/url][/div]
[/div]
[/div]
